workflows:
  unsigned-swift-build:
    name: Unsigned Swift Build
    environment:
      xcode: 15.5
    scripts:
      - name: Resolve SPM & Pods
        script: |
          set -e
          PROJECT_NAME="Your Ai Wallpaper"
          [ -f Podfile ] && pod install --repo-update
          xcodebuild -resolvePackageDependencies \
                     -project "${PROJECT_NAME}.xcodeproj" \
                     -scheme "${PROJECT_NAME}"

      - name: Build .app (Release, 无签名)
        script: |
          set -e
          PROJECT_NAME="Your Ai Wallpaper"
          ARCHIVE_PATH="${PWD}/build/${PROJECT_NAME}.xcarchive"
          xcodebuild archive \
                -project "${PROJECT_NAME}.xcodeproj" \
                -scheme "${PROJECT_NAME}" \
                -configuration Release \
                -archivePath "${ARCHIVE_PATH}" \
                CODE_SIGNING_ALLOWED=NO \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGN_IDENTITY="" \
                PROVISIONING_PROFILE_SPECIFIER=""

      - name: Export .app 并打包
        script: |
          set -e
          PROJECT_NAME="Your Ai Wallpaper"
          APP_PATH=$(find "${PWD}/build" -name "${PROJECT_NAME}.app" -type d | head -n1)
          if [[ -z "$APP_PATH" ]]; then
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "${PROJECT_NAME}.app" -type d | head -n1)
          fi
          mkdir -p build/ios
          cp -R "${APP_PATH}" build/ios/
          cd build/ios
          zip -r "${PROJECT_NAME}.app.zip" "${PROJECT_NAME}.app"
    artifacts:
      - build/ios/Your Ai Wallpaper.app.zip